[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/alecthomas/chroma"
  revision = "v0.9.4"

[[override]]
  name = "github.com/dlclark/regexp2"
  revision = "v1.4.0"

[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"
