on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@main
      with:
        go-version: 1.25.x
    - uses: actions/checkout@main
      with:
         path: './src/github.com/kevinburke/chroma-markdown'
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
    - name: Run tests
      run: make test
      working-directory: './src/github.com/kevinburke/chroma-markdown'
